FROM openjdk
WORKDIR usr/lib
ADD ./target/User_Authentication_Service-0.0.1-SNAPSHOT.jar /usr/lib/User_Authentication_Service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","User_Authentication_Service-0.0.1-SNAPSHOT.jar"]